[package]
name = "plum_message"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
anyhow = "1.0"
cid = { version = "0.5" , features = ["cbor", "json"] }
minicbor = { version = "0.4", features = ["std"] }
multihash = "0.11"
serde = { version = "1.0", features = ["derive"] }

# plum
plum_address = { path = "../address" }
plum_bigint = { path = "../bigint" }
plum_bytes = { path = "../bytes" }
plum_crypto = { path = "../crypto" }
plum_types = { path = "../types" }

[dev-dependencies]
serde_json = "1.0"
