[package]
name = "plum_bitfield"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
minicbor = { version = "0.4", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"

rleplus = { path = "rleplus" }

# plum
plum_bytes = { path = "../bytes" }

[dev-dependencies]
serde_json = "1.0"
