[package]
name = "plum-beacon"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"
build = "build.rs"

[build-dependencies]
protobuf-build = { version = "0.11", default-features = false, features = ["grpcio-prost-codec"] }

[dependencies]
futures = "0.3"
prost = "0.6"
grpcio = { version = "0.6", default-features = false, features = ["openssl-vendored", "prost-codec"] }
