[package]
name = "plum_vm"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

# plum
plum_message = { path = "../primitives/message" }
