[package]
name = "plum_peerid"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
libp2p-core = "0.21"
minicbor = { version = "0.5", features = ["std"] }
serde = "1.0"
