[package]
name = "sigs"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"

[dependencies]
bls = { package = "bls-signatures", version = "0.5" }
rand = "0.7"
anyhow = "1.0"
libsecp256k1 = "0.3"

hashing = { path = "../hashing", package = "plum_hashing" }
