[package]
name = "wallet"
version = "0.1.0"
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
edition = "2018"

[dependencies]
bls = { package = "bls-signatures", version = "0.3" }
libsecp256k1 = { version = "0.3.0" }
derive_more = { version = "0.99.2"}
hex = "0.4.0"
rand = "0.7.2"
serde_json = "1.0.41"
parking_lot = "0.9.0"
failure = "0.1.6"

address = {path = "../address"}
