[package]
name = "wallet"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
bls = { package = "bls-signatures", version = "0.3" }
libsecp256k1 = { version = "0.3.0" }
derive_more = { version = "0.99.2"}
serde_json = "1.0.41"
parking_lot = "0.9.0"
hex = "0.4.0"
thiserror = "1.0"
tempfile = "3.1.0"

address = {path = "../address"}
