[package]
name = "wallet"
version = "0.1.0"
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls = { package = "bls-signatures", version = "0.3" }
varint = { package = "unsigned-varint", version = "0.2.3" }
blake2-rfc = { package = "blake2-rfc", version = "0.2.18" }
libsecp256k1 = { version = "0.3.0" }
derive_more = { version = "0.99.2"}
data-encoding = { package = "data-encoding", version = "2.0.0"}
