[package]
name = "plum-vm-exitcode"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
minicbor = { version = "0.5", features = ["std"] }
serde = "1.0"
serde_repr = "0.1"
