[package]
name = "plum-network-p2p"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
async-trait = "0.1"
cid = { version = "0.5" , features = ["cbor", "json"] }
futures = "0.3"
log = "0.4"
minicbor = { version = "0.4", features = ["std"] }
multihash = "0.11"

plum_bigint = { path = "../../primitives/bigint" }
plum_block = { path = "../../primitives/block" }
plum_message = { path = "../../primitives/message" }
plum_types = { path = "../../primitives/types" }

[dependencies.libp2p]
version = "0.21"
default-features = false
features = [
    "dns",
    "identify",
    "kad",
    "gossipsub",
    "mdns",
    "mplex",
    "ping",
    "request-response",
    "secio",
    "secp256k1",
    "tcp-async-std",
    "yamux",
]
