[package]
name = "plum_crypto"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
bls-signatures = "0.6"
libsecp256k1 = "0.3"
minicbor = { version = "0.5", features = ["std"] }
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
thiserror = "1.0"

# plum
plum_address = { path = "../address" }
plum_bytes = { path = "../bytes" }
plum-hashing = { path = "../../hashing" }

[dev-dependencies]
serde_json = "1.0"
