[package]
name = "plum_bytes"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
base64 = "0.12"
hex = "0.4"
minicbor = { version = "0.5", features = ["std"] }
serde = "1.0"
