[package]
name = "specs-storage"
version = "0.1.0"
authors = ["PolkaX <github.com/polkax>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
cid = { version = "0.5", features = ["impl-serde"] }

plum_actor = { path = "../chain/actor" }
