[package]
name = "plum_sector"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
cid = { version = "0.5", features = ["impl-serde"] }
minicbor = { version = "0.4", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"

# plum
plum_bigint = { path = "../bigint" }
plum_bytes = { path = "../bytes" }
plum_types = { path = "../types" }

[dev-dependencies]
serde_json = "1.0"
