[package]
name = "plum_block"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
cid = { version = "0.4", features = ["impl-serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"

plum_address = { path = "../address" }
plum_bigint = { path = "../bigint" }
plum_crypto = { path = "../../crypto" }
plum_message = { path = "../message" }
plum_ticket = { path = "../ticket" }

[dev-dependencies]
serde_cbor = "0.11.1"
