[package]
name = "plum_block"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"

cid = { git = "https://github.com/PolkaX/rust-cid", branch = "ext", features = ["impl-serde"] }

plum_address = { path = "../../chain/address" }
plum_bigint = { path = "../../chain/bigint" }
plum_crypto = { path = "../../crypto" }
plum_message = { path = "../message" }
plum_ticket = { path = "../ticket" }

[dev-dependencies]
serde_cbor = "0.11.1"
