[package]
name = "plum_block"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
cid = { version = "0.5" , features = ["cbor", "json"] }
minicbor = { version = "0.5", features = ["std"] }
multihash = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"

# plum
plum_address = { path = "../address" }
plum_bigint = { path = "../bigint" }
plum_bytes = { path = "../bytes" }
plum_crypto = { path = "../crypto" }
plum_message = { path = "../message" }
plum_sector = { path = "../sector" }
plum_types = { path = "../types" }
