[package]
name = "cli"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
structopt = "0.3"
tokio = "0.1"
exit-future = "0.1"
lp2p = { path = "../lp2p" }
log = "0.4"
env_logger = "0.7.0"
