[package]
name = "plum_network"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
anyhow = "1.0"
async-std = "1.5"
futures = "0.3"
log = "0.4.8"
plum_libp2p = { path = "../libp2p", package = "plum_libp2p" }
thiserror = "1.0"
