[package]
name = "plum_tipset"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
cid = { version = "0.5", features = ["impl-serde"] }
minicbor = { version = "0.4", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

# plum
plum_bigint = { path = "../bigint" }
plum_block = { path = "../block" }

[dev-dependencies]
hex = "0.4"
multihash = "0.11"
serde_json = "1.0"

plum_address = { path = "../address" }
plum_crypto = { path = "../../crypto" }
