[package]
name = "plum_tipset"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
cid = { version = "0.5" , features = ["cbor", "json"] }
minicbor = { version = "0.5", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

# plum
plum_bigint = { path = "../bigint" }
plum_block = { path = "../block" }
plum_types = { path = "../types" }

[dev-dependencies]
hex = "0.4"
multihash = "0.11"
serde_json = "1.0"

plum_address = { path = "../address" }
plum_crypto = { path = "../crypto" }
