[package]
name = "plum_types"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
cid = { version = "0.4", features = ["impl-serde"] }
serde = { version = "1.0", features = ["derive"] }

plum_bigint = { path = "../bigint" }
