[package]
name = "plum_types"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
cid = { version = "0.5" , features = ["cbor", "json"] }
lazy_static = "1.4"
minicbor = { version = "0.4", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }

# plum
plum_address = { path = "../address" }
plum_bigint = { path = "../bigint" }
plum_hash = { path = "../hash" }
