[package]
name = "ipfs-blockstore"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
cid = { version = "0.5", features = ["cbor", "json"] }
multibase = "0.8"

ipfs-block = { path = "../block" }
ipfs-datastore = { path = "../datastore" }
