[package]
name = "ipfs-blockstore"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
anyhow = "1.0"
cid = { version = "0.5", features = ["cbor", "json"] }

ipfs-block = { path = "../block" }
