[package]
name = "ipfs-block"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
cid = "0.5"
minicbor = { version = "0.5", features = ["std"] }
multihash = "0.11"
