[package]
name = "codec-serde-support"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
primitive-types = { version = "0.6" }
serde = { version = "1.0", features = [ "derive" ] }
serde_bytes = "0.11"
