[package]
name = "peermgr"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
log = "0.4"
libp2p = { version = "0.13", default-features = false }
futures = "0.3.1"
