[package]
name = "peermgr"
license = "GPL-3.0"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = { version = "0.12.0", default-features = false }
lp2p = { path = "../lp2p" }
log = "0.4.8"
