[package]
name = "plum_ticket"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
base64 = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"

[dev-dependencies]
serde_cbor = "0.11.1"
serde_json = "1.0"
