[package]
name = "plum_bigint"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
minicbor = { version = "0.4", features = ["std"] }
num-bigint = "0.2"
num-traits = "0.2"
serde = "1.0"

[dev-dependencies]
serde_derive = "1.0"
serde_json = "1.0"
