[package]
name = "plum_address"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
data-encoding = "2.1"
lazy_static = "1.4"
minicbor = { version = "0.5", features = ["std"] }
serde = "1.0"
thiserror = "1.0"
unsigned-varint = "0.4"

# plum
plum-hashing = { path = "../../hashing" }

[dev-dependencies]
bls-signatures = "0.6"
libsecp256k1 = "0.3"
rand = "0.7"
serde_json = "1.0"
