[package]
name = "plum_ipfs_datastore"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
path-clean = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
