[package]
name = "plum_chain"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
cid = { version = "0.5" , features = ["cbor", "json"] }
data-encoding = "2.1"
lazy_static = "1.4"

# plum
plum_address = { path = "../primitives/address" }
