[package]
name = "chain"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
cid = { version = "0.4", features = ["impl-serde"] }
data-encoding = "2.1"
lazy_static = "1.4"

plum_address = { path = "../primitives/address" }
