[package]
name = "plum_hash"
version = "0.1.0"
authors = ["The PolkaX Authors"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
fixed-hash = "0.6"
minicbor = { version = "0.3", features = ["std"] }
serde = "1.0"

plum_bytes = { path = "../bytes" }
